module.exports = {
  User: require('./User'),
  Category: require('./Category'),
  Product: require('./Product'),
  Order: require('./Order'),
  Review: require('./Review'),
  Coupon: require('./Coupon'),
  Blog: require('./Blog'),
  Complaint: require('./Complaint'),
  Feedback: require('./Feedback'),
  Contact: require('./Contact'),
  Subscription: require('./Subscription'),
  Wholesale: require('./Wholesale'),
  Story: require('./Story'),
  HomePoster: require('./HomePoster'),
  Slider: require('./Slider'),
  AboutUs: require('./AboutUs'),
  ContactPage: require('./ContactPage'),
  StoreLocator: require('./StoreLocator'),
  PrivacyPolicy: require('./PrivacyPolicy'),
  ShippingPolicy: require('./ShippingPolicy'),
  TermAndCondition: require('./TermAndCondition'),
  ReturnPolicy: require('./ReturnPolicy'),
  Cart: require('./Cart'),
  Wishlist: require('./Wishlist'),
  
};